### ISSUE TITLE
complete all TODOs in  CONTRIBUTING.md file

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#128]

**Comment by maeste** [comment]
@fl4via I've added the file as part of general initial documentation commits. That said it needs a review to complete the TODOs as soon as #111 will be completed

**Comment by maeste** [comment]
renaming the issue to reflect this

**Comment by fl4via** [comment]
@maeste I couldn't find any TODO in the contributing or makefile guide. For that reason, I'm closing this issue. If you believe this is a mistake, please reopen it.
