### ISSUE TITLE
Reenable test_tools.py tests

### ISSUE THREAD

**Issue by kabir** [wise-agents/wise-agents#164]
When working on https://github.com/wise-agents/wise-agents/pull/162 I was not able to get some of the tests to pass neither locally, nor on GitHub Actions. This was with the LLM, vectordb, graphdb and artemis running so I believe there is a problem with the test(s).

I skipped `test_agent_tool()` and `test_tool()`, which will need reenabling.

**Comment by fjuma** [comment]
test_coordinator.py and test_tools.py both make use of llama3.1 (instead of Phi-3-mini-4k-instruct-q4.gguf). So we'll also need to install and start Ollama.

**Comment by fjuma** [comment]
Using Groq might be a good option for these tests.
