### ISSUE TITLE
Investigate tests marked with `@pytest.mark.needsllm`

### ISSUE THREAD

**Issue by kabir** [wise-agents/wise-agents#165]
When working on https://github.com/wise-agents/wise-agents/pull/162 I was not able to get some of the tests to pass on GitHub Actions where we are not able to install the LLM due to space constraints.

I excluded some tests there by adding the `@pytest.mark.needsllm` marker.

It isn't totally clear to me in ALL cases whether an LLM is actually needed or not by the test, so it would be great to verify if this is possible.

Another thing could be to investigate if there is a 'mini LLM' that could work in GH Actions.

**Comment by fjuma** [comment]
Using Groq might be a good option for these tests.

**Comment by maeste** [comment]
Dublicate #195
