### ISSUE TITLE
Consider stateless vs staefull implementation of openAI-api_wise_agent_LLM

### ISSUE THREAD

**Issue by maeste** [wise-agents/wise-agents#213]
Curently we have only one implementation. The behavior is completely different though if you call process_chat_completion or process_single_prompt. It's stateless in the first case (for example also system_message is responsibility of the calling client), it's somehow stateful (system_message at least, but could be more messages) in the second case.
Maybe it would be clear in terms of public API to have 2 different classes

**Comment by fjuma** [comment]
Just to check, are you thinking of one class that implements process_chat_completion only and a second class that only implements process_single_prompt?
