### ISSUE TITLE
Optional parameters for OpenAI queries should be exposed somehow

### ISSUE THREAD

**Issue by ehsavoie** [wise-agents/wise-agents#259]
Currently it is not possible to specify temperature, topP or seed for example when interacting with OpenAI

**Comment by maeste** [comment]
I see your point. Ad the system message is part of agent's responsibility, probably also openai parameters should be agent's responsibility. This mean they could be exposed in agent configuration or may be part of hard coded parameters for some specific agent (tag for example)

@fjuma your opinion?

**Comment by fjuma** [comment]
I think it would be good to update the `process_chat_completion` and `process_single_prompt` methods to be able to take optional params to configure this and then this could be added to the agent configuration since we also have the ability to specify the system message there as @maeste mentioned.
