### ISSUE TITLE
CUDA failures

### ISSUE THREAD

**Issue by maeste** [wise-agents/wise-agents#275]
With ptorch CUDA enabled we have these test failures 
========================================================================================================== short test summary info ===========================================================================================================
FAILED tests/wiseagents/test_yaml_serializtion.py::test_using_deserialized_agent - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacity of 15.61 GiB of which 30.00 MiB is free. Process 80631 has 5.89 GiB memory in use. Including non-PyTorch memory, this process has 9.5...
FAILED tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_create_and_delete_collection - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacity of 15.61 GiB of which 30.00 MiB is free. Process 80631 has 5.89 GiB memory in use. Including non-PyTorch memory, this process has 9.5...
FAILED tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_insert_documents_and_query - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacity of 15.61 GiB of which 30.00 MiB is free. Process 80631 has 5.89 GiB memory in use. Including non-PyTorch memory, this process has 9.5...
FAILED tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_insert_or_update_documents_and_query - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacity of 15.61 GiB of which 30.25 MiB is free. Process 80631 has 5.89 GiB memory in use. Including non-PyTorch memory, this process has 9.5...
FAILED tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_delete_documents - torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 90.00 MiB. GPU 0 has a total capacity of 15.61 GiB of which 30.25 MiB is free. Process 80631 has 5.89 GiB memory in use. Including non-PyTorch memory, this process has 9.5...
ERROR tests/wiseagents/vectordb/test_PGVectorLangChainWiseAgentVectorDB.py::test_delete_documents - ExceptionGroup: errors while tearing down <Session  exitstatus=<ExitCode.OK: 0> testsfailed=5 testscollected=28> (2 sub-exceptions)
================================================================================== 5 failed, 20 passed, 3 skipped, 16 warnings, 1 error in 94.74s (0:01:34) ==================================================================================

Forcing pytorch to use CPU with this env variable all of the pass:
(.venv) maeste@fedora ~/project/wise-agents (maeste/issue47 *+) $ export CUDA_VISIBLE_DEVICES=""

**Comment by fjuma** [comment]
Note that `test_Neo4jLangChainWiseAgentGraphDB` also relies on `HuggingFaceEmbeddings` being instantiated successfully. Would be good to check if that test is actually passing or not (I don't see it in the list of failures above but not sure if it's getting skipped or throwing an error or something).

**Comment by maeste** [comment]
@fjuma FYI, after all my fixes merged, it seems this issue has gone away (I tried unsettling that env variable). Most likely the stop_agent I added at the end of each test avoiding multiple executions had helped

**Comment by fjuma** [comment]
Ok thanks, will close for now and we can re-open if needed.
