### ISSUE TITLE
Create some common snippets for set up steps required for the examples

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#303]
Many examples will likely provide steps for cloning the repo, doing other setup required to run the example, etc.

We might want to create some common snippets so that they can be easily used in multiple examples. 

See https://github.com/wise-agents/wise-agents/pull/302#discussion_r1764002006.

**Comment by maeste** [comment]
Except the first 2 example which are part of docs, we can create a general document for requirements.
I'll do a proposal soon with the next example I'll work on. Assigning to me for this iteration
