### ISSUE TITLE
Add a github action to publish mkdocs pages

### ISSUE THREAD

**Issue by maeste** [wise-agents/wise-agents#338]
As per discussion here https://wise-agents.zulipchat.com/#narrow/stream/451287-dev/topic/PR.20reviews

**Comment by kabir** [comment]
@maeste @fjuma Do you have the current steps for building/uploading the docs?

**Comment by fjuma** [comment]
@kabir The current steps are described here: https://github.com/wise-agents/wise-agents.github.io
