### ISSUE TITLE
Review the agent implementations in wise_agent_impl to determine if we should move some of them to a test class instead

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#85]
It might also make sense to pull out related implementations into separate modules (e.g., agents related to rag could be together, agents related to coordination could be together, etc.) instead of having everything in one file.

**Comment by fjuma** [comment]
@maeste Here's a potential proposal and also some questions, let me know what you think:

* We could create a new `wiseagents.agents` package
* We could add a new module, `rag_wise_agents.py` in the new package that contains `RAGWiseAgent`, `GraphRAGWiseAgent`, `CoVeChallengerRAGWiseAgent`
* We could add a new module, `collaboration_wise_agents.py` in the new package that contains `SequentialCoordinatorWiseAgent`, `PhasedCoordinatorWiseAgent`, and `CollaboratorWiseAgent`.

That leaves:

* `LLMOnlyWiseAgent`: This implementation uses `process_single_prompt` and is primarily used for test purposes. Should we move this implementation to the tests?

* `PassThroughClientAgent`: This is used for the CLI and also for testing purposes but this seems general enough that it probably could be part of the `wiseagents.agents` package. WDYT? Any preferences for the name of the module this could go in?

* `LLMWiseAgentWithTools`: We have an issue created to track adding support for tools to a `CollaboratorWiseAgent`. Where do we want `LLMWiseAgentWithTools` to live?

**Comment by maeste** [comment]
> [@maeste](https://github.com/maeste) Here's a potential proposal and also some questions, let me know what you think:
> 
> * We could create a new `wiseagents.agents` package
> * We could add a new module, `rag_wise_agents.py` in the new package that contains `RAGWiseAgent`, `GraphRAGWiseAgent`, `CoVeChallengerRAGWiseAgent`
> * We could add a new module, `collaboration_wise_agents.py` in the new package that contains `SequentialCoordinatorWiseAgent`, `PhasedCoordinatorWiseAgent`, and `CollaboratorWiseAgent`.
> 
Cool!

> That leaves:
> 
> * `LLMOnlyWiseAgent`: This implementation uses `process_single_prompt` and is primarily used for test purposes. Should we move this implementation to the tests?

Yup it could be moved to tests or live in the module with the next 2

> * `PassThroughClientAgent`: This is used for the CLI and also for testing purposes but this seems general enough that it probably could be part of the `wiseagents.agents` package. WDYT? Any preferences for the name of the module this could go in?
> * `LLMWiseAgentWithTools`: We have an issue created to track adding support for tools to a `CollaboratorWiseAgent`. Where do we want `LLMWiseAgentWithTools` to live?

We can put both (or all the three) in something like utility_wise_agents.py. WDYT?

Maybe we can also rename wise_agent.py (containing the abstract classes for agents and Registry and Context) to something like wise_agent_core.py. WDYT?

@fjuma If you have a spare cycle, please go on with this refractory (maybe just leave back wise_agent.py for the moment on which I'm doing a lot of refactoring for supporting Redis for registry and context)

**Comment by fjuma** [comment]
That all sounds good, thanks. I'll go on with the refactoring aside from wise_agent.py.
