### ISSUE TITLE
make sure that tests that update the registry clean up after themselves

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#86]
`test_send_message_to_agent_and_get_response` fails when all of the tests are run using pytest but passes when run individually.

Because this test makes use of `WiseAgentRegistry` and that has a class variable for the `agents` and the `contexts`, other tests that also register agents can interfere with this one when all of the tests are being run (as opposed to just running this test individually).

We should make sure that tests that update the registry clean up after themselves.

**Comment by maeste** [comment]
changed the title to better reflect the real problem.

Moreover as the original title we may want to "Fix test_wise_agent_message_exchange.py " to avoid it depends too much to what the registry contains, but in the end the failure is a side effect of other tests don't cleaning the registry

it could require

- [ ] Adding a clean-up method to the registry and/or context
- [ ] Be sure all tests implement a call to the above method
