### ISSUE TITLE
Determine the format of the final answer to be sent by the coordinator agent

### ISSUE THREAD

**Issue by fjuma** [wise-agents/wise-agents#95]
The coordinator agent will need to be able to determine when the answer is complete and will need to send that final answer back to the user. It would be good to include sources that were used to generate the response or perhaps links to find out more details, etc.

**Comment by fjuma** [comment]
I think we could introduce a final answer agent/tool that could be invoked once we have the final response to format it in the desired manner. See https://github.com/wise-agents/wise-agents/discussions/179 for more details on how this final answer agent could be invoked by the coordinator.

**Comment by maeste** [comment]
+1

**Comment by fjuma** [comment]
Closing this one since https://github.com/wise-agents/wise-agents/pull/207 added the ability to output the final answer. Created https://github.com/wise-agents/wise-agents/issues/237 to track adding the ability to include information about the sources that were consulted to achieve the final answer to the output as well.
